---
name: Terracove
description: Use the Terracove CLI in a github action
author: jatalocks
inputs:
  path:
    description: The Directory Tree Root
    default: "."
    required: true
  ignore-errors:
    description: Ignore Planning Errors
    default: "false"
    required: false
  ignore-empty:
    description: Ignore Modules with 0 Resources
    default: "false"
    required: false
  html:
    description: Create an HTML Report
    default: "true"
    required: false
  json:
    description: Create a JSON Report
    default: "true"
    required: false
  junit:
    description: Create a Junit XML Report
    default: "true"
    required: false
  minimal:
    description: Don't Append Raw/JSON Plan to the Exported Output
    default: "false"
    required: false
  o-html:
    description: Create an HTML Report
    default: "terracove.html"
    required: false
  o-json:
    description: Create a JSON Report
    default: "terracove.json"
    required: false
  o-junit:
    description: Create a Junit XML Report
    default: "terracove.xml"
    required: false
  validate-tf-by:
    description: Validate terraform by the existence of [filename]
    default: "main.tf"
    required: false
  validate-tg-by:
    description: Validate terragrunt by the existence of [filename]
    default: "terragrunt.hcl"
    required: false
  exclude:
    description: Exclude directories using a comma separated list
    default: ""
    required: false
runs:
  using: docker
  image: "docker://ghcr.io/jatalocks/terracove"
  args:
    - ${{ inputs.path }}
    - --html=${{ inputs.html }}
    - --json=${{ inputs.json }}
    - --junit=${{ inputs.junit }}
    - --minimal=${{ inputs.minimal }}
    - --ignore-errors=${{ inputs.ignore-errors }}
    - --ignore-empty=${{ inputs.ignore-empty }}
    - --o-html=${{ inputs.o-html }}
    - --o-json=${{ inputs.o-json }}
    - --o-junit=${{ inputs.o-junit }}
    - --validate-tf-by=${{ inputs.validate-tf-by }}
    - --validate-tg-by=${{ inputs.validate-tg-by }}
    - --exclude=${{ inputs.exclude-dirs }}
branding:
  icon: "layers"
  color: "purple"
