name: Test and coverage

on:
  push:
    branches:
      - master
  pull_request:

jobs:
  test:
    strategy:
      matrix:
        go-version: [1.19.x]
        os: [ubuntu-latest, macos-latest]

    runs-on: ${{ matrix.os }}

    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 2

      - uses: actions/setup-go@v4
        with:
          go-version: ${{ matrix.go-version }}

      - name: go get
        run: go get ./...

      - name: go mod tidy
        run: go mod tidy

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2.0.3

      - name: Setup Terragrunt
        uses: eLco/setup-terragrunt@v1.0.2

      - name: Run coverage
        run: |
          go test -v -race $(go list ./... | grep -v /vendor/) -v -coverprofile=coverage.out

      - name: Upload coverage to Codecov
        if: matrix.os == 'ubuntu-latest'
        run: bash <(curl -s https://codecov.io/bash)
